# Generated by Django 4.2.7 on 2023-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registereduser_berat_badan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='gender',
            field=models.CharField(choices=[('Laki-laki', 'Laki Laki'), ('Perempuan', 'Perempuan')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='tingkat_aktivitas',
            field=models.CharField(choices=[('Level_1', 'Level 1'), ('Level_2', 'Level 2'), ('Level_3', 'Level 3'), ('Level_4', 'Level 4'), ('Level_5', 'Level 5')], default='Level_1'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='umur',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
