# Generated by Django 4.2.7 on 2023-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('idArtikel', models.IntegerField()),
                ('judulArtikel', models.CharField()),
                ('isiArtikel', models.TextField(blank=True)),
                ('tanggalDiunggah', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
