# Generated by Django 4.2.7 on 2023-12-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_remove_artikel_idartikel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='userId',
        ),
    ]
