name: KaloriKu Backend CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        run: python manage.py test
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USER: ${{secrets.DB_USER}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}

  database-migration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migration
        run: python manage.py migrate
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USER: ${{secrets.DB_USER}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
    if: github.ref == 'refs/heads/main'

  publish:
    runs-on: ubuntu-latest
    needs: database-migration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest
          build-args: |
            DB_HOST: ${{secrets.DB_HOST}}
            DB_NAME: ${{secrets.DB_NAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_USER: ${{secrets.DB_USER}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
    if: github.ref == 'refs/heads/main'

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Chmod private key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.GCLOUD_SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: SSH to google cloud
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.GCP_USERNAME}}@${{secrets.EXTERNAL_IP}} "
          docker container rm -f kaloriku_backend || true &&
          docker image rm -f ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest || true &&
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest &&
          docker run --name kaloriku_backend -d -p 8000:8000 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest"
    if: github.ref == 'refs/heads/main'